In [1]:
import numpy as np

In [2]:
# scalar multiplication to a row
def scalar_multiplication_to_a_row(matrix, row_idx, scalar):
    result = np.array(matrix)
    
    result[row_idx] = scalar * matrix[row_idx]
    return result

In [3]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
result = scalar_multiplication_to_a_row(matrix=A, row_idx=0, scalar=2)
print(result)

[[2 4 6]
 [4 5 6]
 [7 8 9]]


In [4]:
# interchange of rows
def interchange_of_rows(matrix, row_idx1, row_idx2):
    result = np.array(matrix)
    
    result[row_idx1] = matrix[row_idx2]
    result[row_idx2] = matrix[row_idx1]
    
    return result

In [5]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
result = interchange_of_rows(matrix=A, row_idx1=0, row_idx2=1)
print(result)

[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [6]:
# linear combination of rows
def linear_combination_of_rows(matrix, coefficients, target_row):
    # coefficients: list of coefficients
    n_rows, n_cols = matrix.shape
    
    result = np.array(matrix)
    for i in range(n_rows):
        if i == target_row:
            result[target_row] += (coefficients[i]-1) * matrix[i] 
        else:
            result[target_row] += coefficients[i] * matrix[i] 
         
    return result             

In [7]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
result = linear_combination_of_rows(A, [1,1,1], 2)
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [12 15 18]]


In [8]:
# using the 3 function above, create a function that solves a system of linear equations and performs gaussian elimination
# system of linear equations: consists of A and b; AX = b
# suppose that A,b are numpy arrays

def gaussian_elimination(matrix): # matrix is a 3 by 4 matrix, including both A and b, where last column is b

    n_rows, n_cols = matrix.shape
    result = np.array(matrix) * 1.0 # make matrix float
    
    # make sure num of rows is one less than num of columns     
    assert n_cols == n_rows + 1

    # 1 find the row that has a non-zero coefficient of X(1)
    # 2 if the first row has a non-zero coefficient of X(1), then leave it there. Otherwise, switch the first row and the row with a non-zero coefficient
    if result[0][0] == 0:
        for i in range(n_rows-1):
            if result[i+1][0] == 0:
                continue
            else:
                result = interchange_of_rows(result, 0, i+1)
                break 
                
    for x in range(n_rows): 
    # 3 divide some number to make the xth element of xth row to be 1
        result[x] = result[x] / result[x][x] # divide by zero
        # 4 make all other rows to have 0 as the first element of the rows (via 3rd function we defined)
        # 5 repeat 3 and 4 for the rest of the elements
        for i in range(n_rows):
            if i == x: # skip row of x because item of idex x,x is 1 
                continue
            else: 
                k = - result[i][x] # will be multiplied to xth row to subtract out of target row (ith row)
                coefficients = [] # to be multiplied to ith row
                for j in range(n_rows):
                    if j == i:
                        coefficients.append(1)
                    elif j == x:
                        coefficients.append(k)
                    else:
                        coefficients.append(0)
                result = linear_combination_of_rows(result, coefficients, i) # subtract the ith row with xth row times xth item of ith row
    print(result)
    
    matrixB = [] # take elements of last column
    for y in range(n_rows):
        matrixB.append(result[y][-1])
        
    return matrixB

In [9]:
A = np.array([
    [3,2,1,9],
    [2,4,1,7],
    [1,1,-1,3]
])
gaussian_elimination(A) # answer: 2.72, 0.36, 0.09

[[ 1.          0.          0.          2.72727273]
 [ 0.          1.          0.          0.36363636]
 [-0.         -0.          1.          0.09090909]]


[2.727272727272727, 0.3636363636363636, 0.09090909090909091]

In [10]:
B = np.array([
    [2,5,2,-38],
    [3,-2,4,17],
    [-6,1,-7,-12]
])
gaussian_elimination(B) # answer: 3, -8, -2

[[ 1.  0.  0.  3.]
 [ 0.  1.  0. -8.]
 [ 0.  0.  1. -2.]]


[2.9999999999999925, -8.0, -1.999999999999995]

In [11]:
C = np.array([
    [0,3,-9,33],
    [-4,7,-1,-15],
    [6,4,5,-6]
])

gaussian_elimination(C) # answer: 3, -1, -4

[[ 1.  0.  0.  3.]
 [ 0.  1.  0. -1.]
 [ 0.  0.  1. -4.]]


[3.0, -1.0, -4.0]

In [12]:
# function that returns the inverse of a matrix
# given x by x matrix 
def inverse(matrix):  

    n_rows, n_cols = matrix.shape
    result = np.array(matrix) * 1.0 # make matrix float
    
    inv_matrix = np.zeros(matrix.shape) # make identity matrix which will later be the inverse matrix
    for i in range(matrix.shape[0]): 
        inv_matrix[i][i] = 1

    # 1 find the row that has a non-zero coefficient of Xth row and Xth column
    # 2 if the diagonal element (Xth row and Xth column) has non-zero, then leave it there. Otherwise, switch with a row with a non-zero element in that column
    for z in range(n_rows):
        if result[z][z] == 0:
            for i in range(n_rows-1):
                if result[i+1][z] == 0:
                    continue
                else:
                    result = interchange_of_rows(result, z, i+1)
                    inv_matrix = interchange_of_rows(inv_matrix, z, i+1)  
                    break 
          
    for x in range(n_rows): # x will represent the index (row and col) of diagonal element
    # 3 divide some number to make the xth element of xth row to be 1
        diag_coef = result[x][x]
        result[x] = result[x] / diag_coef 
        inv_matrix[x] = inv_matrix[x] / diag_coef

        # 4 make all other rows to have 0 as the first element of the rows (via 3rd function we defined)
        # 5 repeat 3 and 4 for the rest of the elements
        for target_row in range(n_rows): # target_row represents the focus row where all elements left of diag will be set to zero
            if target_row == x: # skip row of x because item of idex x,x is 1 
                continue
            else: 
                k = - result[target_row][x] # will be multiplied to xth row to subtract out of target row 
                coefficients = [] # will be multiplied to rows 
                for target_col in range(n_rows):
                    if target_col == target_row: # we want the target row as is (so multiply row with 1) 
                        coefficients.append(1)
                    elif target_col == x: # we want to multiply xth row with k to subtract out of target row
                        coefficients.append(k)
                    else: # other than xth row and target row, we do not need other rows
                        coefficients.append(0)

                result = linear_combination_of_rows(result, coefficients, target_row) # subtract the ith row with xth row times xth item of ith row
                inv_matrix = linear_combination_of_rows(inv_matrix, coefficients, target_row)

    return inv_matrix

In [17]:
A = np.array([ 
    [2,5,2],
    [3,-2,4],
    [-6,1,-7]
])
print(inverse(A)) # inverse of matrix
np.around(A @ inverse(A),2) # matrix times inverse of matrix

[[-0.76923077 -2.84615385 -1.84615385]
 [ 0.23076923  0.15384615  0.15384615]
 [ 0.69230769  2.46153846  1.46153846]]


array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

In [18]:
B = np.array([
    [3,2,1],
    [2,4,1],
    [1,1,-1]
])
print(inverse(B)) # inverse of matrix
np.around(B @ inverse(B)) # matrix times inverse of matrix

[[ 0.45454545 -0.27272727  0.18181818]
 [-0.27272727  0.36363636  0.09090909]
 [ 0.18181818  0.09090909 -0.72727273]]


array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [-0.,  0.,  1.]])