### Matrix functions without numpy (includes multiplication, transpose, rotations, determinant)

In [19]:
class Matrix:
    def __init__(self, data): # initialize
        self.n_rows = len(data)
        self.n_cols = len(data[0])
        self.data = data # a list of lists
        
    def __call__(self):
        return 'Matrix defined in a {} by {} space: {}'.format(self.n_rows, self.n_cols, self.data) 
    
    def __add__(self, other): # add two matrices
        assert self.n_rows == other.n_rows
        assert self.n_cols == other.n_cols
        new_matrix = []
        for i in range(self.n_rows): 
            temp = []
            for j in range(self.n_cols):
                temp.append(self.data[i][j] + other.data[i][j])
                
            new_matrix.append(temp)
            
        return Matrix(new_matrix)
    
    def __sub__(self, other): # subtracts two matrices
        assert self.n_rows == other.n_rows
        assert self.n_cols == other.n_cols
        new_matrix = []
        for i in range(self.n_rows): 
            temp = []
            for j in range(self.n_cols):
                temp.append(self.data[i][j] - other.data[i][j])
                
            new_matrix.append(temp)
            
        return Matrix(new_matrix)
        
    def scalar_mul(self, scalar): # scalar multiplication
        new_matrix = []
        for i in range(self.n_rows):
            temp = []
            for j in range(self.n_cols):
                temp.append(self.data[i][j] * scalar)
                
            new_matrix.append(temp)
            
        return Matrix(new_matrix)
    
    def vector_mul(self, vector): # vector multiplication
        assert self.n_cols == len(vector)
        new_matrix = []
        for i in range(self.n_rows):
            temp = []
            for j in range(self.n_cols):
                temp.append(self.data[i][j] * vector[j])
                
            new_matrix.append(temp)
            
        return Matrix(new_matrix)
    
    def matrix_mul(self, other): # matrix-matrix multiplication
        assert self.n_cols == other.n_rows
        new_matrix = []
        for i in range(self.n_rows):
            temp_list = []
            for k in range(other.n_cols):
                temp_value = 0
                for j in range(self.n_cols):
                    temp_value += self.data[i][j] * other.data[j][k]
                temp_list.append(temp_value)
                
            new_matrix.append(temp_list)
            
        return Matrix(new_matrix)
    
    def norm(self): # find norm of matrix
        value = 0
        for i in range(self.n_rows):
            for j in range(self.n_cols):
                value += self.data[i][j]**2
            
        result = value**(1/2)
        
        return result
     
    def row_sum(self): # find sum of rows of matrix
        result = ZeroMatrix(1, self.n_cols)
        for j in range(self.n_cols):
            temp_sum = 0
            for i in range(self.n_rows):
                temp_sum += self.data[i][j]
                
            result.data[0][j] = temp_sum
            
        return result

    def col_sum(self): # find sum of columns of matrix
        result = ZeroMatrix(self.n_rows, 1)
        for i in range(self.n_rows):
            temp_sum = 0
            for j in range(self.n_cols):
                temp_sum += self.data[i][j]
            result.data[i][0] = temp_sum
            
        return result
        
    def total_sum(self): # find total sum of matrix
        result = 0
        for i in range(self.n_rows):
            result += sum(self.data[i])
        return result
    
    def transpose(self): # return transpose of matrix
        result = []
        for i in range(len(self.data[0])):
            temp = []
            for j in range(len(self.data)):
                temp.append(self.data[j][i])
            
            result.append(temp)
        return result
    
    def rotate_clockwise(self): # rotate the matrix values clockwise
        x = len(self.data)
        y = len(self.data[0])
        result = []
        for j in range(y):
            temp = []
            for i in range(x):
                temp.append(self.data[-i-1][j])

            result.append(temp)

        return result

    def rotate_counterclockwise(self): # rotate the matrix values counter clockwise
        x = len(self.data)
        y = len(self.data[0])
        result = []
        for j in range(y):
            temp = []
            for i in range(x):
                temp.append(self.data[i][-j-1])

            result.append(temp)

        return result


In [20]:
A = Matrix([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(A.transpose())
print(A.rotate_clockwise())
print(A.rotate_counterclockwise())

[[1, 4, 7, 10], [2, 5, 8, 11], [3, 6, 9, 12]]
[[10, 7, 4, 1], [11, 8, 5, 2], [12, 9, 6, 3]]
[[3, 6, 9, 12], [2, 5, 8, 11], [1, 4, 7, 10]]


In [21]:
class ZeroMatrix(Matrix): # make matrix of zeros
    def __init__(self, m, n):
        temp_data = []
        for i in range(m):
            temp = []
            for j in range(n):
                temp.append(0)
            temp_data.append(temp)
        super().__init__(temp_data)

In [22]:
# find determinant of matrix
def det(matrix):

    if matrix.n_rows == 2:
        return (matrix.data[0][0] * matrix.data[1][1]) - (matrix.data[0][1] * matrix.data[1][0])
    
    n_sub_rows = matrix.n_rows - 1
    n_sub_cols = matrix.n_cols - 1
    sub_matrix = ZeroMatrix(n_sub_cols, n_sub_rows)
    
    final_value = 0
    plus_minus = -1

    for i in range(matrix.n_cols):
        
        sub_matrix_row = 0
        for j in range(n_sub_rows):
            sub_matrix_col = 0
            for k in range(matrix.n_cols):
                if i == k:
                    continue
                else:
                    sub_matrix.data[sub_matrix_row][sub_matrix_col] = matrix.data[j+1][k]
                    sub_matrix_col += 1
            sub_matrix_row += 1

        det_value = det(sub_matrix)
        
        multiplied_value = matrix.data[0][i] * det_value
        
        plus_minus = plus_minus * (-1) 
        final_value = final_value + (plus_minus * multiplied_value)
    
    return final_value

In [23]:
C = Matrix([[5,6,7],[4,5,6],[1,8,9]])
det(C)

-6

In [24]:
D = Matrix([[5,6,7,3],[4,5,6,5],[1,8,9,6],[2,3,4,1]])
det(D)

48

### Matrix function with numpy (includes gaussian elimination and inverse of matrix)

In [25]:
import numpy as np

In [26]:
# scalar multiplication to a row
def scalar_multiplication_to_a_row(matrix, row_idx, scalar):
    result = np.array(matrix)
    
    result[row_idx] = scalar * matrix[row_idx]
    return result

In [27]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
result = scalar_multiplication_to_a_row(matrix=A, row_idx=0, scalar=2)
print(result)

[[2 4 6]
 [4 5 6]
 [7 8 9]]


In [28]:
# interchange of rows
def interchange_of_rows(matrix, row_idx1, row_idx2):
    result = np.array(matrix)
    
    result[row_idx1] = matrix[row_idx2]
    result[row_idx2] = matrix[row_idx1]
    
    return result

In [29]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
result = interchange_of_rows(matrix=A, row_idx1=0, row_idx2=1)
print(result)

[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [30]:
# linear combination of rows
def linear_combination_of_rows(matrix, coefficients, target_row):
    # coefficients: list of coefficients
    n_rows, n_cols = matrix.shape
    
    result = np.array(matrix)
    for i in range(n_rows):
        if i == target_row:
            result[target_row] += (coefficients[i]-1) * matrix[i] 
        else:
            result[target_row] += coefficients[i] * matrix[i] 
         
    return result             

In [31]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
result = linear_combination_of_rows(A, [1,1,1], 2)
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [12 15 18]]


In [32]:
# using the 3 function above, create a function that solves a system of linear equations and performs gaussian elimination
# system of linear equations: consists of A and b; AX = b
# suppose that A,b are numpy arrays

def gaussian_elimination(matrix): # matrix is a 3 by 4 matrix, including both A and b, where last column is b

    n_rows, n_cols = matrix.shape
    result = np.array(matrix) * 1.0 # make matrix float
    
    # make sure num of rows is one less than num of columns     
    assert n_cols == n_rows + 1

    # 1 find the row that has a non-zero coefficient of X(1)
    # 2 if the first row has a non-zero coefficient of X(1), then leave it there. Otherwise, switch the first row and the row with a non-zero coefficient
    if result[0][0] == 0:
        for i in range(n_rows-1):
            if result[i+1][0] == 0:
                continue
            else:
                result = interchange_of_rows(result, 0, i+1)
                break 
                
    for x in range(n_rows): 
    # 3 divide some number to make the xth element of xth row to be 1
        result[x] = result[x] / result[x][x] # divide by zero
        # 4 make all other rows to have 0 as the first element of the rows (via 3rd function we defined)
        # 5 repeat 3 and 4 for the rest of the elements
        for i in range(n_rows):
            if i == x: # skip row of x because item of idex x,x is 1 
                continue
            else: 
                k = - result[i][x] # will be multiplied to xth row to subtract out of target row (ith row)
                coefficients = [] # to be multiplied to ith row
                for j in range(n_rows):
                    if j == i:
                        coefficients.append(1)
                    elif j == x:
                        coefficients.append(k)
                    else:
                        coefficients.append(0)
                result = linear_combination_of_rows(result, coefficients, i) # subtract the ith row with xth row times xth item of ith row
    print(result)
    
    matrixB = [] # take elements of last column
    for y in range(n_rows):
        matrixB.append(result[y][-1])
        
    return matrixB

In [33]:
A = np.array([
    [3,2,1,9],
    [2,4,1,7],
    [1,1,-1,3]
])
gaussian_elimination(A) # answer: 2.72, 0.36, 0.09

[[ 1.          0.          0.          2.72727273]
 [ 0.          1.          0.          0.36363636]
 [-0.         -0.          1.          0.09090909]]


[2.727272727272727, 0.3636363636363636, 0.09090909090909091]

In [34]:
B = np.array([
    [2,5,2,-38],
    [3,-2,4,17],
    [-6,1,-7,-12]
])
gaussian_elimination(B) # answer: 3, -8, -2

[[ 1.  0.  0.  3.]
 [ 0.  1.  0. -8.]
 [ 0.  0.  1. -2.]]


[2.9999999999999925, -8.0, -1.999999999999995]

In [35]:
C = np.array([
    [0,3,-9,33],
    [-4,7,-1,-15],
    [6,4,5,-6]
])

gaussian_elimination(C) # answer: 3, -1, -4

[[ 1.  0.  0.  3.]
 [ 0.  1.  0. -1.]
 [ 0.  0.  1. -4.]]


[3.0, -1.0, -4.0]

In [36]:
# function that returns the inverse of a matrix
# given x by x matrix 
def inverse(matrix):  

    n_rows, n_cols = matrix.shape
    result = np.array(matrix) * 1.0 # make matrix float
    
    inv_matrix = np.zeros(matrix.shape) # make identity matrix which will later be the inverse matrix
    for i in range(matrix.shape[0]): 
        inv_matrix[i][i] = 1

    # 1 find the row that has a non-zero coefficient of Xth row and Xth column
    # 2 if the diagonal element (Xth row and Xth column) has non-zero, then leave it there. Otherwise, switch with a row with a non-zero element in that column
    for z in range(n_rows):
        if result[z][z] == 0:
            for i in range(n_rows-1):
                if result[i+1][z] == 0:
                    continue
                else:
                    result = interchange_of_rows(result, z, i+1)
                    inv_matrix = interchange_of_rows(inv_matrix, z, i+1)  
                    break 
          
    for x in range(n_rows): # x will represent the index (row and col) of diagonal element
    # 3 divide some number to make the xth element of xth row to be 1
        diag_coef = result[x][x]
        result[x] = result[x] / diag_coef 
        inv_matrix[x] = inv_matrix[x] / diag_coef

        # 4 make all other rows to have 0 as the first element of the rows (via 3rd function we defined)
        # 5 repeat 3 and 4 for the rest of the elements
        for target_row in range(n_rows): # target_row represents the focus row where all elements left of diag will be set to zero
            if target_row == x: # skip row of x because item of idex x,x is 1 
                continue
            else: 
                k = - result[target_row][x] # will be multiplied to xth row to subtract out of target row 
                coefficients = [] # will be multiplied to rows 
                for target_col in range(n_rows):
                    if target_col == target_row: # we want the target row as is (so multiply row with 1) 
                        coefficients.append(1)
                    elif target_col == x: # we want to multiply xth row with k to subtract out of target row
                        coefficients.append(k)
                    else: # other than xth row and target row, we do not need other rows
                        coefficients.append(0)

                result = linear_combination_of_rows(result, coefficients, target_row) # subtract the ith row with xth row times xth item of ith row
                inv_matrix = linear_combination_of_rows(inv_matrix, coefficients, target_row)

    return inv_matrix

In [37]:
A = np.array([ 
    [2,5,2],
    [3,-2,4],
    [-6,1,-7]
])
print(inverse(A)) # inverse of matrix
np.around(A @ inverse(A),2) # matrix times inverse of matrix

[[-0.76923077 -2.84615385 -1.84615385]
 [ 0.23076923  0.15384615  0.15384615]
 [ 0.69230769  2.46153846  1.46153846]]


array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

In [38]:
B = np.array([
    [3,2,1],
    [2,4,1],
    [1,1,-1]
])
print(inverse(B)) # inverse of matrix
np.around(B @ inverse(B)) # matrix times inverse of matrix

[[ 0.45454545 -0.27272727  0.18181818]
 [-0.27272727  0.36363636  0.09090909]
 [ 0.18181818  0.09090909 -0.72727273]]


array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [-0.,  0.,  1.]])