In [1]:
import numpy as np

In [2]:
# for a given square matrix AER ^(mxn), return the pair of principal eigen value and vector using power iteration
def power_iteration(matrix, iteration): # matrix is an n by n square matrix
    n_rows, n_cols = matrix.shape
    
    V = [1] # make any random unit vector (||X|| = 1)
    for i in range(n_rows-1):
        V.append(0)
        
    for i in range(iteration):
        V = matrix @ V
        V = V / (np.dot(V,V) ** (1/2)) # normalize the vector
        
    eigen_vector = V # principal eigen vector
    
    eigen_value = (V.T @ matrix.T @ V) / np.dot(V,V) # principal eigen value
    
    return eigen_vector, eigen_value

In [3]:
A = np.array([[8,3],[2,7]])
print(power_iteration(A, 10000)) 
print(A @ np.array([0.83205029, 0.5547002]))
print(9.999 * np.array([0.83205029, 0.5547002]))

(array([0.83205029, 0.5547002 ]), 9.999999999999998)
[8.32050292 5.54700198]
[8.31967085 5.5464473 ]


In [4]:
B = np.array([[5,3,2],[8,3,2],[2,4,1]])
print(power_iteration(B, 10000)) 
print(B @ np.array([0.55543318, 0.71580643, 0.42321996]))
print(10.39013389129487 * np.array([0.55543318, 0.71580643, 0.42321996]))

(array([0.55543318, 0.71580643, 0.42321996]), 10.39013389129487)
[5.77102511 7.43732465 4.39731204]
[5.77102511 7.43732465 4.39731205]
